version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: url_shortener_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: 